language: python

python:
  - "3.7"

os:
  - "linux"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

scripts: timeout 10s knut.py --conf=etc/knutserver.yml
