language: python

python:
  - "3.7"

os:
  - "linux"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

scripts: knutserver -f etc/example.yml & sleep 10 && kill -SIGINT $!
